/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useMemo } from 'react';
import { Plus, Trash2, Cpu, FileCode, CheckCircle, Copy, Check, Sparkles, RefreshCcw, Download } from 'lucide-react';
import { SnapshotConfig } from '../types';

export default function InteractiveBuilder() {
  const [v8Major, setV8Major] = useState<number>(12);
  const [v8Minor, setV8Minor] = useState<number>(4);
  const [v8Patch, setV8Patch] = useState<number>(1);
  const [formatVersion, setFormatVersion] = useState<number>(3);
  
  const [strictMode, setStrictMode] = useState<boolean>(true);
  const [pointerCompression, setPointerCompression] = useState<boolean>(true);
  const [sandboxEnabled, setSandboxEnabled] = useState<boolean>(true);
  const [turbofanEnabled, setTurbofanEnabled] = useState<boolean>(true);

  const [externalRefs, setExternalRefs] = useState<string[]>([
    'v8::internal::Runtime_MathSqrt',
    'v8::internal::Runtime_DateNow',
    'v8::internal::Runtime_StringAdd'
  ]);
  const [newRefName, setNewRefName] = useState<string>('');
  
  const [copiedCode, setCopiedCode] = useState<string | null>(null);
  const [verificationResult, setVerificationResult] = useState<'idle' | 'success'>('idle');

  // Input Sanitizer ensuring only positive integers are parsed
  const handleV8MajorChange = (val: string) => {
    const sanitized = val.replace(/[^0-9]/g, '');
    const parsed = parseInt(sanitized, 10);
    setV8Major(isNaN(parsed) ? 1 : Math.max(1, parsed));
  };

  const handleV8MinorChange = (val: string) => {
    const sanitized = val.replace(/[^0-9]/g, '');
    const parsed = parseInt(sanitized, 10);
    setV8Minor(isNaN(parsed) ? 0 : parsed);
  };

  const handleV8PatchChange = (val: string) => {
    const sanitized = val.replace(/[^0-9]/g, '');
    const parsed = parseInt(sanitized, 10);
    setV8Patch(isNaN(parsed) ? 0 : parsed);
  };

  const addRef = () => {
    if (newRefName.trim() && !externalRefs.includes(newRefName.trim())) {
      setExternalRefs([...externalRefs, newRefName.trim()]);
      setNewRefName('');
    }
  };

  const removeRef = (idx: number) => {
    setExternalRefs(externalRefs.filter((_, i) => i !== idx));
  };

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedCode(id);
    setTimeout(() => setCopiedCode(null), 2000);
  };

  // Compile Flags bit calculation
  const calculatedFlags = useMemo(() => {
    let flagVal = 0;
    if (strictMode) flagVal |= 1 << 0;
    if (pointerCompression) flagVal |= 1 << 2;
    if (sandboxEnabled) flagVal |= 1 << 3;
    if (turbofanEnabled) flagVal |= 1 << 5;
    return flagVal;
  }, [strictMode, pointerCompression, sandboxEnabled, turbofanEnabled]);

  // FNV-1a simple implementation on string
  const fnv1a_64_hash = (str: string): string => {
    let hash = 0xcbf29ce484222325n;
    const prime = 0x100000001b3n;
    for (let i = 0; i < str.length; i++) {
      hash = hash ^ BigInt(str.charCodeAt(i));
      hash = (hash * prime) & 0xffffffffffffffffn;
    }
    return '0x' + hash.toString(16).toUpperCase() + 'ULL';
  };

  // Generate dynamic C++ Loader Boilerplate
  const generatedCpp = useMemo(() => {
    const symbolListCode = externalRefs.map((symbol, idx) => {
      const hashStr = fnv1a_64_hash(symbol);
      return `    { ${hashStr}, (intptr_t)&${symbol.replace(/::/g, '_')} } /* ${symbol} */`;
    }).join(',\n');

    return `/**
 * =========================================================================
 * 🛡️ AUTOGENERATED SECURE V8 SNAPSHOT COMPATIBLE LOADER (C++)
 * Built according to V8 Snapshot Contract Protocol (Format V${formatVersion})
 * =========================================================================
 */
#include <stdint.h>
#include <string.h>
#include <sys/mman.h>

#define SNAPSHOT_MAGIC 0x56385300
#define EXPECTED_V8_MAJOR ${v8Major}
#define EXPECTED_V8_MINOR ${v8Minor}
#define EXPECTED_FLAGS_MASK 0x${calculatedFlags.toString(16).toUpperCase()}

struct SnapshotHeader {
    uint8_t  magic[4];
    uint32_t format_version;
    uint32_t v8_major;
    uint32_t v8_minor;
    uint32_t v8_patch;
    uint32_t flags;
    uint32_t num_contexts;
    uint32_t section_count;
    uint32_t payload_offset;
    uint32_t payload_size;
    uint32_t checksum;
    uint32_t reloc_table_offset;
    uint32_t reloc_table_size;
    uint32_t external_ref_count;
} __attribute__((packed));

struct ExternalRefEntry {
    uint64_t name_hash;
    intptr_t address;
};

/* Compiled system bindings matching your interactive design */
static const ExternalRefEntry HostExternalRefTable[] = {
${symbolListCode || '    /* No dynamic bindings configured */'}
};
static const size_t HostExternalRefTableSize = ${externalRefs.length};

SnapshotError load_and_verify_metadata(const uint8_t* blob_bytes, size_t size) {
    if (size < sizeof(SnapshotHeader)) {
        return SNAPSHOT_ERR_IO_TRUNCATED;
    }

    const SnapshotHeader* header = (const SnapshotHeader*)blob_bytes;

    /* Verify Magic Contract */
    if (*(uint32_t*)header->magic != SNAPSHOT_MAGIC) {
        return SNAPSHOT_ERR_MAGIC;
    }

    /* Verify Engine Versioning */
    if (header->v8_major != EXPECTED_V8_MAJOR) {
        return SNAPSHOT_ERR_V8_MAJOR_MISMATCH;
    }

    /* Verify Sandboxed Feature flags */
    if ((header->flags & EXPECTED_FLAGS_MASK) != EXPECTED_FLAGS_MASK) {
        return SNAPSHOT_ERR_FLAG_INCOMPATIBLE;
    }

    /* Verify external reference lengths */
    if (header->external_ref_count > HostExternalRefTableSize) {
        return SNAPSHOT_ERR_EXT_REF_SHORT;
    }

    return SNAPSHOT_OK;
}
`;
  }, [v8Major, v8Minor, v8Patch, formatVersion, calculatedFlags, externalRefs]);

  const verifyCustomConfig = () => {
    setVerificationResult('idle');
    setTimeout(() => {
      setVerificationResult('success');
    }, 400);
  };

  const downloadConfigJson = () => {
    const configData: SnapshotConfig = {
      magic: '56385300',
      formatVersion,
      v8Major,
      v8Minor,
      v8Patch,
      flags: {
        strictMode,
        embeddedBuiltins: true,
        pointerCompression,
        sandboxEnabled,
        shortBuiltinCalls: false,
        turbofanEnabled,
      },
      numContexts: 1,
      externalRefCount: externalRefs.length,
      payloadOffset: 64,
      payloadSize: 1048576,
      alignment: 4096,
      customSections: [
        { type: 4, name: 'READ_ONLY_SPACE', size: 65536, alignment: 4096, mmapPermission: 'r--' },
        { type: 1, name: 'CODE_SPACE', size: 524288, alignment: 4096, mmapPermission: 'r-x' },
        { type: 2, name: 'MAP_SPACE', size: 131072, alignment: 4096, mmapPermission: 'rw-' },
        { type: 3, name: 'OLD_SPACE', size: 262144, alignment: 4096, mmapPermission: 'rw-' },
        { type: 5, name: 'SHARED_SPACE', size: 32768, alignment: 4096, mmapPermission: 'r--' },
        { type: 6, name: 'LARGE_OBJECT_SPACE', size: 32768, alignment: 4096, mmapPermission: 'rw-' },
      ],
      relocRecords: [
        { sectionIdx: 1, offset: 0x100 },
        { sectionIdx: 1, offset: 0x400 },
        { sectionIdx: 2, offset: 0x200 },
        { sectionIdx: 3, offset: 0x12a0 },
        { sectionIdx: 3, offset: 0x5800 },
      ],
      externalRefs: [...externalRefs],
      optionalMask: Array(externalRefs.length).fill(false),
    };

    const jsonString = JSON.stringify(configData, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `v8-snapshot-config-v${formatVersion}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
      {/* Parameter inputs list */}
      <div className="lg:col-span-5 bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-5">
        <div className="border-b border-slate-800 pb-3">
          <h4 className="font-display font-semibold text-slate-100 text-md flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-indigo-400" />
            1. 自定义快照配置
          </h4>
          <p className="text-slate-400 text-xs mt-1">
            定义你的 V8 项目环境属性。系统会在右侧自动编译并构建安全哈希对齐的 C++ 宿主快照 Loader 代码件。
          </p>
        </div>

        {/* Inputs */}
        <div className="space-y-4 text-xs font-mono">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-slate-400 mb-1">格式协议版本</label>
              <input
                type="number"
                min="1"
                step="1"
                value={formatVersion}
                onChange={(e) => setFormatVersion(Math.max(1, parseInt(e.target.value) || 3))}
                className="w-full bg-slate-950 border border-slate-800 p-2 text-amber-400 rounded focus:outline-none"
              />
            </div>
            <div>
              <label className="block text-slate-400 mb-1 flex justify-between">
                <span>V8 Engine Major</span>
                {(v8Major < 5 || v8Major > 16) && <span className="text-amber-500 font-bold font-sans">⚠️ 异常</span>}
              </label>
              <input
                type="number"
                min="1"
                step="1"
                value={v8Major}
                onChange={(e) => handleV8MajorChange(e.target.value)}
                className={`w-full bg-slate-950 border p-2 text-slate-100 rounded focus:outline-none transition-all ${
                  v8Major < 5 || v8Major > 16 
                    ? 'border-amber-500/50 focus:border-amber-500 bg-amber-950/10' 
                    : 'border-slate-800 focus:border-indigo-500'
                }`}
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-slate-400 mb-1 flex justify-between">
                <span>V8 Engine Minor</span>
                {v8Minor > 15 && <span className="text-amber-500 font-bold font-sans">⚠️ 异常</span>}
              </label>
              <input
                type="number"
                min="0"
                step="1"
                value={v8Minor}
                onChange={(e) => handleV8MinorChange(e.target.value)}
                className={`w-full bg-slate-950 border p-2 text-slate-100 rounded focus:outline-none transition-all ${
                  v8Minor > 15 
                    ? 'border-amber-500/50 focus:border-amber-500 bg-amber-950/10' 
                    : 'border-slate-800 focus:border-indigo-500'
                }`}
              />
            </div>
            <div>
              <label className="block text-slate-400 mb-1 flex justify-between">
                <span>V8 Engine Patch</span>
                {v8Patch > 300 && <span className="text-amber-500 font-bold font-sans">⚠️ 异常</span>}
              </label>
              <input
                type="number"
                min="0"
                step="1"
                value={v8Patch}
                onChange={(e) => handleV8PatchChange(e.target.value)}
                className={`w-full bg-slate-950 border p-2 text-slate-100 rounded focus:outline-none transition-all ${
                  v8Patch > 300 
                    ? 'border-amber-500/50 focus:border-amber-500 bg-amber-950/10' 
                    : 'border-slate-800 focus:border-indigo-500'
                }`}
              />
            </div>
          </div>

          {/* V8 Version Constraints Warnings */}
          {(v8Major < 5 || v8Major > 16 || v8Minor > 15 || v8Patch > 300) && (
            <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg p-3 text-[11px] text-amber-400 font-sans space-y-1">
              <span className="font-semibold block text-amber-300">⚠️ V8 版本契约警示 (Standard V8 Version Warnings):</span>
              {v8Major < 5 && (
                <p>• Major version ({v8Major}) 偏低。低于 v5 的 V8 引擎可能不完全兼容 V3 头部反序列化契约架构。</p>
              )}
              {v8Major > 16 && (
                <p>• Major version ({v8Major}) 偏高。超过 v16 的 V8 引擎属于未来/前沿版本，可能会有 ABI 接口不稳定的情况。</p>
              )}
              {v8Minor > 15 && (
                <p>• Minor version ({v8Minor}) 偏高。标准 V8 微版本生命期中单个主迭代内的 Minor 鲜少超过 15。</p>
              )}
              {v8Patch > 300 && (
                <p>• Patch level ({v8Patch}) 过高。包含过度定制或非官方分支的漏洞修复可能伴随 relocatable table 内存重叠风险。</p>
              )}
            </div>
          )}

          {/* Compilation configurations */}
          <div className="bg-slate-950 p-4 border border-slate-800 rounded-lg space-y-2 font-sans">
            <span className="text-[11px] font-mono text-slate-400 block border-b border-slate-800 pb-1.5 uppercase font-medium">配置选项 (Compiled flags):</span>
            
            <div className="grid grid-cols-2 gap-2 text-xs">
              <label className="flex items-center space-x-2 text-slate-400 cursor-pointer">
                <input
                  type="checkbox"
                  checked={strictMode}
                  onChange={(e) => setStrictMode(e.target.checked)}
                  className="rounded border-slate-800 text-indigo-600 bg-slate-900"
                />
                <span>Strict Mode</span>
              </label>

              <label className="flex items-center space-x-2 text-slate-400 cursor-pointer">
                <input
                  type="checkbox"
                  checked={pointerCompression}
                  onChange={(e) => setPointerCompression(e.target.checked)}
                  className="rounded border-slate-800 text-indigo-600 bg-slate-900"
                />
                <span>Pointer Comp</span>
              </label>

              <label className="flex items-center space-x-2 text-slate-400 cursor-pointer">
                <input
                  type="checkbox"
                  checked={sandboxEnabled}
                  onChange={(e) => setSandboxEnabled(e.target.checked)}
                  className="rounded border-slate-800 text-indigo-600 bg-slate-900"
                />
                <span>V8 Sandbox</span>
              </label>

              <label className="flex items-center space-x-2 text-slate-400 cursor-pointer">
                <input
                  type="checkbox"
                  checked={turbofanEnabled}
                  onChange={(e) => setTurbofanEnabled(e.target.checked)}
                  className="rounded border-slate-800 text-indigo-600 bg-slate-900"
                />
                <span>Turbofan</span>
              </label>
            </div>
          </div>

          {/* Dynamic External references table creator */}
          <div className="bg-slate-950 p-4 border border-slate-800 rounded-lg space-y-3 font-sans">
            <span className="text-[11px] font-mono text-slate-400 block border-b border-slate-800 pb-1.5 uppercase font-medium flex justify-between">
              <span>动态外部引用集 ({externalRefs.length} 个)</span>
              <span className="text-[9px] text-pink-400">R-01/R-08 保护</span>
            </span>

            {/* List of references */}
            <div className="space-y-1.5 max-h-40 overflow-y-auto pr-1 scrollbar">
              {externalRefs.map((ref, idx) => (
                <div key={idx} className="flex items-center justify-between text-xs font-mono bg-slate-900 p-2 border border-slate-800 rounded">
                  <span className="text-[10px] text-indigo-300 truncate" title={ref}>{ref}</span>
                  <button
                    onClick={() => removeRef(idx)}
                    className="text-slate-500 hover:text-rose-400 p-0.5 transition cursor-pointer"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              ))}
            </div>

            {/* Input to append item */}
            <div className="flex gap-1.5">
              <input
                type="text"
                placeholder="v8::internal::Runtime_MathAbs"
                value={newRefName}
                onChange={(e) => setNewRefName(e.target.value)}
                className="flex-1 bg-slate-900 text-xs border border-slate-800 px-2.5 py-1.5 rounded font-mono focus:outline-none"
              />
              <button
                onClick={addRef}
                className="bg-indigo-600 hover:bg-indigo-500 text-white p-2.5 rounded transition flex items-center justify-center cursor-pointer"
              >
                <Plus className="w-4 h-4" />
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Dynamic C++ Generated Source */}
      <div className="lg:col-span-7 flex flex-col space-y-5">
        <div className="bg-slate-950 border border-slate-800 rounded-xl overflow-hidden flex flex-col h-[520px]">
          <div className="bg-slate-900 px-5 py-3 flex items-center justify-between border-b border-slate-800 pb-3">
            <div className="flex items-center space-x-2">
              <FileCode className="w-5 h-5 text-indigo-400" />
              <h4 className="font-display font-semibold text-slate-100 text-sm">
                动态定制 C++ Loader 模板代码
              </h4>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={downloadConfigJson}
                className="flex items-center gap-1.5 text-xs text-amber-400 bg-slate-950 hover:bg-slate-850 px-2.5 py-1.5 rounded border border-slate-800 font-mono transition cursor-pointer"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download Config</span>
              </button>

              <button
                onClick={() => copyToClipboard(generatedCpp, 'cpp-generator')}
                className="flex items-center gap-1.5 text-xs text-indigo-400 bg-slate-950 hover:bg-slate-850 px-2.5 py-1.5 rounded border border-slate-800 font-mono transition cursor-pointer"
              >
                {copiedCode === 'cpp-generator' ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span className="text-emerald-400">已拷贝!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    <span>Copy Source Code</span>
                  </>
                )}
              </button>
            </div>
          </div>

          <pre className="flex-1 p-5 overflow-y-auto font-mono text-[10.5px] text-emerald-400 bg-slate-950 border-none leading-relaxed select-text scrollbar">
            {generatedCpp}
          </pre>
        </div>

        {/* Verifier Trigger widget */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="text-xs text-slate-400 max-w-md">
            <span className="font-semibold text-slate-200 block mb-0.5">契约合规性检测 (Loader Conformity Checker)</span>
            点击测试以运行自检，对你生成的 V8 宿主 C++ 签名、哈希链以及标志对齐状况进行模拟安全性检测。
          </div>

          <div className="flex items-center gap-2">
            {verificationResult === 'success' && (
              <span className="text-emerald-400 text-xs font-mono font-semibold flex items-center gap-1">
                <CheckCircle className="w-4 h-4 animate-bounce" />
                CONFORMING_WORK_OK ✅
              </span>
            )}
            <button
              onClick={verifyCustomConfig}
              className="bg-indigo-600 hover:bg-indigo-500 whitespace-nowrap text-white px-4 py-2.5 rounded text-xs font-display font-medium flex items-center gap-1.5 transition cursor-pointer"
            >
              <Cpu className="w-4 h-4" />
              自检校验契约
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
